return table.freeze({
	AutoTrain = "AutoTrain",
	Store = "Store",
	Inventory = "Inventory",
	Travel = "Travel",
	Rebirth = "Rebirth",
	Codes = "Codes",
	Friends = "Friends",
	Settings = "Settings",
	Rewards = "Rewards",
	DailyRewards = "DailyRewards",
	Spins = "Spins",
	TradeRequest = "TradeRequest",
	TradeList = "TradeList",
	Trade = "Trade",
	Season = "Season",
	StarterPack = "StarterPack",
	Rejoin = "Rejoin",
	OfflineFarm = "OfflineFarm",
	OfflineNotification = "OfflineNotification",
	UpdateLog = "UpdateLog",
	Team = "Team",
	SelectCharacter = "SelectCharacter",
	MergeCharacters = "MergeCharacters",
	Packs = "Packs",
	Customize = "Customize",
})
