return table.freeze({
	["Onboarding"] = {
		First_Auto_On_Join = true,

		[1] = "Join the game",
		[2] = "Completed first match",
		[3] = "Bought coach",
		[4] = "Trained shooting stats",
		[5] = "Trained passing stats",
		[6] = "Trained dribbling stats",
		[7] = "Completed second match",
		[8] = "Bought character pack",
		[9] = "Equipped character",
		[10] = "Bought accessory",
		[11] = "Equipped accessory",
		[12] = "Completed tutorial",
	},

	["Progress"] = {
		[1] = {
			Tab_Name = "Progression",
			First_Auto_On_Join = true,

			[1] = "Join the game",
			[2] = "Unlocked second area",
			[3] = "Unlocked third area",
			[4] = "Unlocked fourth area",
			[5] = "Unlocked fifth area",
		},
	},

	["Economy"] = {
		In_Game = {
			Money2 = 0,
			Wins = 0,
			Rebirth = 0,
		},

		Robux = {
			["Accessory - Clutch Mascot"] = "Product",
			["Accessory - Angel Wings"] = "Product",
			["Accessory - Gauntlet"] = "Product",
			["Accessory - GOAT Shoes"] = "Product",
			["Boost Bundle"] = "Product",
			["Daily Rewards - Buy All"] = "Product",
			["Daily Rewards - Skip 1"] = "Product",
			["Rebirth - Skip 1"] = "Product",
			["Rebirth - Skip 5"] = "Product",
			["Time Rewards - Buy 2"] = "Product",
			["Time Rewards - Buy All"] = "Product",
			["Wins Pack - Big"] = "Product",
			["Wins Pack - Huge"] = "Product",
			["Wins Pack - Regular"] = "Product",
			["Wins Pack - Small"] = "Product",
			["x1 Premium Spins"] = "Product",
			["x10 Free Pet"] = "Product",
			["x10 Free Spins"] = "Product",
			["x10 Premium Spins"] = "Product",
			["x30 Free Spins"] = "Product",
			["x1 Elite Contract Pack"] = "Product",
			["x5 Elite Contract Pack"] = "Product",
			["x10 Elite Contract Pack"] = "Product",
			["x1 Superstar Vault"] = "Product",
			["x5 Superstar Vault"] = "Product",
			["x10 Superstar Vault"] = "Product",
			["x2 Wins Boost"] = "Product",
			["x2 Passing Boost"] = "Product",
			["x2 Shooting Boost"] = "Product",
			["x2 Dribbling Boost"] = "Product",
			["Coach - Jos Morningho"] = "Product",
			["Coach - Saar Alex Ferguyon"] = "Product",
			["Refill Pack"] = "Product",

			["Lucky"] = "GamePasses",
			["x10 Open"] = "GamePasses",
			["Super Lucky"] = "GamePasses",
			["x5 Open"] = "GamePasses",
			["Ultra Lucky"] = "GamePasses",
			["VIP"] = "GamePasses",
			["x2 Dribble"] = "GamePasses",
			["x2 Pass"] = "GamePasses",
			["x2 Shoot"] = "GamePasses",
			["x2 Rebirths"] = "GamePasses",
			["x2 Wins"] = "GamePasses",
			["+25 Storage"] = "GamePasses",
			["+50 Storage"] = "GamePasses",
			["Season Pass - Premium"] = "GamePasses",

			["Starter Pack"] = "Packs",

			-- Season Pass
			["Season Pass - Skip 1"] = "Product",
			["Season Pass - Skip All"] = "Product",
			["Battle Pass - Plus"] = "Product",
			["Battle Pass - Regular"] = "Product",
		},
	},
})
